#!/bin/sh
# Renova Backup start up script
# Fabricio Kury -- fabriciokury@gmail.com -- github.com/fabkury

echo "Starting Renova Backup."
nohup /opt/bin/python /shares/fabriciokury/Arquivo/Trabalhos/RB/rb.py >/dev/null 2>&1 &
exit 0
